# Generated by Django 5.2.1 on 2025-05-07 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, default='data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAMAAzAMBIgACEQEDEQH/xAAbAAEBAQADAQEAAAAAAAAAAAAAAQUDBAYCB//EADIQAQACAQIDBQUHBQAAAAAAAAABAgMEEQUhMRITQVFxIlJhcpEUFSQzU2LBMkJEobH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABYRAQEBAAAAAAAAAAAAAAAAAAABEf/aAAwDAQACEQMRAD8A/KAFQAAAAAAAAAAAAAAAAAAAAAABAUSFABAJNwAVFAAAAAAAEWAAAEVOQKgAQqKAACQqKAioCoACooAG4J6cyOc7RHPyafDuGd/WMufeuOelfebOHBjwViMVK0iPKOa4PMV02e0b1w5Jj5ZLafNSN74ckR5zWXqpjf4+pt6GDyM8p2SHqs+lw56zGSkT8Y5SwdforaSYmJ7WOeljB1AEBFQA8AAlUUABBFBQABNhQAADd2eHaeNTqqY5jekc7ejqtngFI7Oa/jvELBrREREREdFHBrdR9m098sc5jlAOceVy58uW82yZbTafj0c2h1uXT5axa9pxzO1omdwekcefFTNitjvHK0bS+4nfmoPJ5sU4slsdutZ2cbR45Ts6uLR/dXeWd4oKigCKAAAIoAAAAAAAACNzgPLT5I/f/DEbfA71rgyRMxv2vGfgsGoz+Nx+Cj54d7vK+9X6s3jeSs6WK9qN5tExEAxJlNxyYadvLSnnMQD1OLljrH7YfaRG0beS+IMXj35uL5ZZLS43ftamlfKrNhBQAAAAAAAAAAABJWAAAAAAQBocGwd9q+8tHs443nbzdGsTa0ViN5npHm9Lw/TRpdPFdvbnnefio7KWnZWfxfVdzgmlZ9vJG0fCPEGNrcvfaq946b7R6OEj13EAEBRFAEhQAAAAAAQJAWBFAAABzaTD9o1FMXhPX0WDS4LpP8nLHOf6In/rXfFaxSsVrG1YjaPR9bxHUHHqMtMOK2S8+zWN5eZ1Oe2oy2yXnr0jyh3uM6qb5YwVn2ac7erM2QUABCQFEAIVIUAAEhUUAAEFARQAAAavAcUTky5fKOzDK6NvgO3cZZ/csGo4tTk7rT5Mnu13crqcUn8Bl28gectabTNrTvM85lDfkIAAJIoAioCgAAAAAAAAAAAAAOzo9bl0kzNNrRPWLOs7/DdBXWVva+SaxWdtojmsHJ99Zv0sf+3FqeKZs+G2OaUrFuuzufcmL9bJ9IfOXg2KmK1q5rzMRM7TsDHjoJ0VAAABAUAAAAEQIVFUQAAAFEUAAEno3OA/k5fm/hiO/wAO19dJW9bUm0WnflPQHoHFqeeDJv7suhPGsX6V/rDizcYpfHatMV95jbnsujJ8IISN/FYQBFBEUANwAiVQBQQFAARUAIADxVPFQAAEUBAAFhFgAAER9SgAAKJCgAAQAAigIKkgKQAAAAAgoAAAAAAAigAAAAP/2Q==', max_length=1000, null=True)),
                ('cost', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('add_at', models.DateTimeField(auto_now=True)),
                ('upt_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posts for selling',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('time_contract', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_title', to='booking.post')),
            ],
            options={
                'verbose_name_plural': 'Book_Others',
                'unique_together': {('title', 'customer')},
            },
        ),
    ]
