# Generated by Django 5.1.7 on 2025-05-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Rent', 'verbose_name_plural': 'Rents'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Selling post', 'verbose_name_plural': 'Posts for selling'},
        ),
    ]
