# Generated by Django 5.1.7 on 2025-05-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_book_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('owner', 'customer')},
        ),
    ]
