# Generated by Django 5.1.7 on 2025-05-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_book_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
