# Generated by Django 5.1.7 on 2025-05-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', 'Чоловік'), ('woman', 'Жінка')], max_length=100, null=True),
        ),
    ]
