# Generated by Django 5.1.7 on 2025-05-06 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_book_options_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_room',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.post')),
                ('room_num', models.CharField(max_length=255)),
            ],
            bases=('booking.post',),
        ),
    ]
